### PR TITLE
fix date bug

### PR DESCRIPTION
**Pull request by imdevarsh**
do not merge until you run `npm init` in this repo and then `npm install cross-fetch` please

### CODE REVIEW

**Comment by imdevarsh** [comment]
once you do the above instructions then should be ready to merge

**Comment by imdevarsh** [comment]
@JaydenDev

**Comment by jdev082** [comment]
Since this org and its repositories can't be considered mine in any way since I didn't at all make them... idk

**Comment by imdevarsh** [comment]
can you do it?? just `npm init -y` and `npm install cross-fetch` thats it, then commit the package lock and package.json

**Comment by jdev082** [comment]
i will transfer the ownership of the organization tomorrow

**Comment by imdevarsh** [comment]
no its because im busy and this is my last change

**Comment by imdevarsh** [comment]
doing it myself

**Pull request merged**
